name: railflow-api-stack

services:

  railflow-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    image: railflow-api:1.0.0

    container_name: railflow-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=4)"
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s